terms
    "1. The Company that Receives Personal Information: LINE Corporation"
    "|br"
    "2. Collected Personal Information: Information of purchased item (Item name, quantity, etc.) and purchase information list"
    "|br"
    "3. Purpose of Collecting and Using Personal Information: To provide item purchase service for users, process user inquiries and complaints, preserve the records for dispute settlement, Etc."
    "|br"
    "4. Storage and Use Period of Personal Information: A certain period of time after LINE POD service withdrawal"
    "|br"
    "5. Notice on the Right to Refuse Consent: You have the right to refuse consent to provide personal information, but in this case, purchase and use of service may be restricted."